language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 3.1
install:
- dotnet restore
cache:
  directories:
    - node_modules
script:
- dotnet build
- dotnet test Src/Tests/DietShopper.Domain.UnitTests/DietShopper.Domain.UnitTests.csproj
